### PR TITLE
Updated Conference Schedule

### PR DESCRIPTION
**Pull request by Nelwhix**
I saw your tweet and updated the schedule for Laracon 2022

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thank you!

**Review by owenvoke — COMMENTED** [review]
I think this needs cleaning up as the lightning talks are split this time (currently it's displaying the lightning talks twice).

**Comment by nunomaduro** [comment]
@Nelwhix This does not seem right.

Screenshot 2022-09-12 at 09 46 00

**Comment by Nelwhix** [comment]
@nunomaduro I am sorry, I am making some changes now

**Comment by owenvoke** [comment]
@Nelwhix, no need to apologise. 👌🏻 Thank you for contributing. 🎉

**Pull request merged**
